#!/usr/bin/env python3
"""submit_rivet4.py - Submit Condor jobs to run Rivet 4 on HepMC2 files.

Usage examples:
  # Submit jobs for all events_*.hepmc.gz in an EOS directory:
  python3 submit_rivet4.py --input-dir /eos/user/g/gsokmen/rivet_hepMC/WG-NPall_400-800 \\
                           --output-dir /eos/user/g/gsokmen/rivet_yoda/WG-NPall_400-800

  # Dry run (print condor submit file, don't submit):
  python3 submit_rivet4.py --input-dir ... --output-dir ... --dry-run
"""
from __future__ import print_function
import argparse
import os
import subprocess
import sys
import glob
import textwrap

# Default paths (adjust if needed) 
CMSSW_SRC = "/afs/cern.ch/work/g/gsokmen/EFT2Obs/CMSSW_15_0_15/src"
EFT2OBS_DIR = os.path.join(CMSSW_SRC, "EFT2Obs")
JOB_SCRIPT = os.path.join(EFT2OBS_DIR, "scripts", "run_rivet4_job.sh")


parser = argparse.ArgumentParser(description="Submit Condor jobs to run Rivet 4 on HepMC2 files")
parser.add_argument("--input-dir", "-i", required=True,
                    help="Directory containing events_*.hepmc.gz files (EOS or AFS)")
parser.add_argument("--output-dir", "-o", required=True,
                    help="Directory for output YODA files (EOS or AFS)")
parser.add_argument("--pattern", default="events_*.hepmc.gz",
                    help="Glob pattern for HepMC files (default: events_*.hepmc.gz)")
parser.add_argument("--job-flavour", default="workday",
                    choices=["espresso", "microcentury", "longlunch", "workday",
                             "tomorrow", "testmatch", "nextweek"],
                    help="Condor job flavour / max wall time (default: workday ~8h)")
parser.add_argument("--memory", default="4000",
                    help="Memory request in MB (default: 4000)")
parser.add_argument("--log-dir", default=None,
                    help="Directory for condor log/out/err files (must be on AFS, not EOS; "
                         "default: <EFT2OBS_DIR>/condor_logs/<basename of output-dir>)")
parser.add_argument("--dry-run", action="store_true",
                    help="Print condor submit file but do not submit")
parser.add_argument("--submit-file", default="rivet4_condor.sub",
                    help="Name for the generated condor submit file (default: rivet4_condor.sub)")
args = parser.parse_args()

input_dir = args.input_dir
output_dir = args.output_dir

if input_dir.startswith("/eos/"):
    # Use eos ls via xrdfs
    eos_path = "root://eosuser.cern.ch/" + input_dir
    try:
        result = subprocess.run(
            ["xrdfs", "root://eosuser.cern.ch", "ls", input_dir],
            capture_output=True, text=True, check=True
        )
        all_files = [input_dir + "/" + os.path.basename(f.strip())
                     for f in result.stdout.splitlines() if f.strip()]
    except subprocess.CalledProcessError:
        print(f"ERROR: Could not list EOS directory: {input_dir}")
        sys.exit(1)
else:
    all_files = sorted(glob.glob(os.path.join(input_dir, args.pattern)))

# Filter by pattern
import fnmatch
input_files = [f for f in all_files if fnmatch.fnmatch(os.path.basename(f), args.pattern)]

if not input_files:
    print(f"ERROR: No files matching '{args.pattern}' found in {input_dir}")
    sys.exit(1)

print(f"Found {len(input_files)} input file(s):")
for f in input_files:
    print(f"  {f}")

# Log dir MUST be on AFS (not EOS) — HTCondor forbids EOS for log/out/err
if args.log_dir:
    log_dir = args.log_dir
else:
    slug = os.path.basename(output_dir.rstrip("/")) or "condor_jobs"
    log_dir = os.path.join(EFT2OBS_DIR, "condor_logs", slug)

if log_dir.startswith("/eos/"):
    print("ERROR: --log-dir must be on AFS (not EOS). "
          "HTCondor does not support EOS for log/out/err files.\n"
          "  See: https://batchdocs.web.cern.ch/troubleshooting/eos.html#no-eos-submission-allowed")
    sys.exit(1)

os.makedirs(log_dir, exist_ok=True)

# Generate condor job list (one line per input file)
job_args = []
for inp in input_files:
    basename = os.path.basename(inp).replace(".hepmc.gz", ".yoda")
    out_yoda = os.path.join(output_dir, basename)
    job_args.append((inp, out_yoda))

# Write job list file (single queue statement reads from this)
list_file = args.submit_file.replace(".sub", "_jobs.txt")
with open(list_file, "w") as f:
    for inp, out in job_args:
        f.write(f"{inp}, {out}\n")

# Write condor submit file — single queue statement to avoid deprecation warning
list_file_abs = os.path.abspath(list_file)
submit_content = textwrap.dedent(f"""\
    # Condor submit file generated by submit_rivet4.py
    # Rivet 4 jobs: HepMC2->HepMC3 conversion + Rivet analysis

    executable   = {JOB_SCRIPT}
    universe     = vanilla

    # Resources
    request_memory = {args.memory}
    +JobFlavour    = "{args.job_flavour}"

    # Output/error/log per job (must be on AFS, not EOS)
    output = {log_dir}/rivet4_$(ClusterId)_$(ProcId).out
    error  = {log_dir}/rivet4_$(ClusterId)_$(ProcId).err
    log    = {log_dir}/rivet4_$(ClusterId).log

    # Copy environment (needed for AFS/EOS paths, VOMS proxy)
    getenv = True

    # Single queue statement (HTCondor >= 25 requires this)
    arguments = $(input_file) $(output_file)
    queue input_file, output_file from {list_file_abs}
""")

with open(args.submit_file, "w") as f:
    f.write(submit_content)

print(f"\nCondor submit file written: {args.submit_file}")
print(f"  Job list: {list_file_abs}")
print(f"  Jobs    : {len(job_args)}")
print(f"  Flavour : {args.job_flavour}")
print(f"  Memory  : {args.memory} MB")
print(f"  Logs    : {log_dir}")

if args.dry_run:
    print("\n[DRY RUN] Not submitting. To submit, run:")
    print(f"  condor_submit {args.submit_file}")
else:
    print("\n>> Submitting to Condor...")
    result = subprocess.run(["condor_submit", args.submit_file],
                            capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print("ERROR:", result.stderr)
        sys.exit(1)
    print(">> Submitted!")
